/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as MyReposIndexRouteImport } from './my-repos/index'
import { Route as topReposIndexRouteImport } from './(top-repos)/index'
import { Route as RepoRepoIdRouteImport } from './repo/$repoId'

const MyReposIndexRoute = MyReposIndexRouteImport.update({
  id: '/my-repos/',
  path: '/my-repos/',
  getParentRoute: () => rootRouteImport,
} as any)
const topReposIndexRoute = topReposIndexRouteImport.update({
  id: '/(top-repos)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoRepoIdRoute = RepoRepoIdRouteImport.update({
  id: '/repo/$repoId',
  path: '/repo/$repoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/repo/$repoId': typeof RepoRepoIdRoute
  '/': typeof topReposIndexRoute
  '/my-repos': typeof MyReposIndexRoute
}
export interface FileRoutesByTo {
  '/repo/$repoId': typeof RepoRepoIdRoute
  '/': typeof topReposIndexRoute
  '/my-repos': typeof MyReposIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/repo/$repoId': typeof RepoRepoIdRoute
  '/(top-repos)/': typeof topReposIndexRoute
  '/my-repos/': typeof MyReposIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/repo/$repoId' | '/' | '/my-repos'
  fileRoutesByTo: FileRoutesByTo
  to: '/repo/$repoId' | '/' | '/my-repos'
  id: '__root__' | '/repo/$repoId' | '/(top-repos)/' | '/my-repos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RepoRepoIdRoute: typeof RepoRepoIdRoute
  topReposIndexRoute: typeof topReposIndexRoute
  MyReposIndexRoute: typeof MyReposIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/my-repos/': {
      id: '/my-repos/'
      path: '/my-repos'
      fullPath: '/my-repos'
      preLoaderRoute: typeof MyReposIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(top-repos)/': {
      id: '/(top-repos)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof topReposIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repo/$repoId': {
      id: '/repo/$repoId'
      path: '/repo/$repoId'
      fullPath: '/repo/$repoId'
      preLoaderRoute: typeof RepoRepoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  RepoRepoIdRoute: RepoRepoIdRoute,
  topReposIndexRoute: topReposIndexRoute,
  MyReposIndexRoute: MyReposIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
