/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as MyReposRouteImport } from './../routes/MyRepos'
import { Route as IndexRouteImport } from './../routes/index'

const MyReposRoute = MyReposRouteImport.update({
  id: '/MyRepos',
  path: '/MyRepos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/MyRepos': typeof MyReposRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/MyRepos': typeof MyReposRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/MyRepos': typeof MyReposRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/MyRepos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/MyRepos'
  id: '__root__' | '/' | '/MyRepos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MyReposRoute: typeof MyReposRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/MyRepos': {
      id: '/MyRepos'
      path: '/MyRepos'
      fullPath: '/MyRepos'
      preLoaderRoute: typeof MyReposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MyReposRoute: MyReposRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
